name: Test Contracts

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14.16.0

    defaults:
      run:
        working-directory: contracts

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            v1-${{ runner.os }}

      - run: yarn install
      - run: yarn run lint:sol
      - run: yarn run test
